// ============================================================
// 展覽現場資料蒐集與採購媒合平台 — 四語資料庫 (tc/sc/ja/en)
// ============================================================
// 每個可翻譯值 = {tc:繁中, sc:簡中, ja:日文, en:英文}
// 資料層級:L1公開 L2 B2B採購 L3管理者內部 L4指定客戶專屬
// ============================================================
function L(tc, sc, ja, en){ return {tc:tc, sc:sc, ja:ja, en:en}; }

// ---------- UI 介面字串 ----------
window.I18N = {
  langNames: { tc:"繁中", sc:"简中", ja:"日本語", en:"English" },
  logo: L("展覽現場資料蒐集與採購媒合平台","展览现场资料搜集与采购媒合平台","展示会情報収集・調達支援システム","Expo Data Collection & Sourcing Platform"),
  logoSub: "展示会情報収集・調達支援システム / 海外展会采购资料管理系统",
  rolePrefix: L("目前身份:","当前身份:","現在のアカウント:","Current role: "),
  switchRole: L("切換身份","切换身份","アカウント切替","Switch role"),
  backHome: L("返回首頁","返回首页","ホームへ戻る","Back to home"),
  home: {
    title: L("請選擇您的身份入口","请选择您的身份入口","アカウントをお選びください","Choose your portal"),
    sub1: L("QR Code / 網站入口 → 系統判斷身份 → 四種專屬入口","QR Code / 网站入口 → 系统判断身份 → 四种专属入口","QRコード / Web入口 → 身分判定 → 4つの専用入口","QR / Web entry → identity check → 4 dedicated portals"),
    levelsTitle: L("四級資料可見層級","四级资料可见层级","4段階の情報公開レベル","Four data-visibility levels"),
    lv1: L("L1 公開資料 — 消費者","L1 公开资料 — 消费者","L1 公開情報 — 消費者","L1 Public — Consumers"),
    lv2: L("L2 B2B採購資料 — 委託採購商","L2 B2B采购资料 — 委托采购商","L2 B2B情報 — バイヤー","L2 B2B — Buyers"),
    lv3: L("L3 管理者內部資料 — 僅管理人","L3 管理者内部资料 — 仅管理人","L3 内部情報 — 管理者のみ","L3 Internal — Admin only"),
    lv4: L("L4 指定客戶專屬 — 特定採購商","L4 指定客户专属 — 特定采购商","L4 指定顧客限定 — 特定バイヤー","L4 Client-specific — Designated buyers"),
    levelsDesc: L("同一筆商品資料分三種版本輸出:展商原始版(管理人)、B2B採購版(委託採購商)、消費者展示版(一般消費者)。管理人控制每一層的開放對象。",
      "同一笔商品资料分三种版本输出:展商原始版(管理人)、B2B采购版(委托采购商)、消费者展示版(一般消费者)。管理人控制每一层的开放对象。",
      "同じ商品データを3つの版で出力:出展者原本版(管理者)、B2B調達版(バイヤー)、消費者展示版(一般消費者)。管理者が各レベルの公開先を制御します。",
      "Each product is output in three versions: exhibitor original (admin), B2B sourcing (buyers), and consumer showcase. The admin controls who sees each level.")
  },
  entries: [
    { id:"exhibitor", ic:"🏭", cls:"n1",
      title:L("展覽廠商 / 出展企業","展览厂商 / 出展企业","出展企業","Exhibitor"),
      ja:"出展企業アカウント",
      desc:L("日本展場廠商。掃碼後上傳並建立自己的公司與商品商務資料。","日本展场厂商。扫码后上传并建立自己的公司与商品商务资料。","日本の出展者。QR読取後、自社・商品の商務情報を登録します。","Japanese exhibitors. Scan the QR to register company and product business data."),
      tag:L("主要語言:日文","主要语言:日文","主要言語:日本語","Primary: Japanese") },
    { id:"buyer", ic:"📋", cls:"n2",
      title:L("委託帶採購廠商","委托带采购厂商","調達依頼企業 / バイヤー","Sourcing Buyer"),
      ja:"調達依頼企業 / 海外バイヤーアカウント",
      desc:L("最重要的 B2B 客戶。查看管理者整理後、授權開放的採購資料。","最重要的 B2B 客户。查看管理者整理后、授权开放的采购资料。","最重要のB2B顧客。管理者が整理・許可した調達情報を閲覧。","Key B2B clients. View curated, authorized sourcing data."),
      tag:L("主要語言:繁中／簡中","主要语言:繁中／简中","主要言語:中国語","Primary: Chinese") },
    { id:"consumer", ic:"🛍️", cls:"n3",
      title:L("傳統消費者","传统消费者","一般消費者","Consumer"),
      ja:"一般消費者アカウント",
      desc:L("一般消費者與社群粉絲。看到簡化、公開的商品展示與導購資訊。","一般消费者与社群粉丝。看到简化、公开的商品展示与导购信息。","一般消費者・SNSファン。簡略化された公開商品情報を閲覧。","General consumers and fans. See simplified public product info."),
      tag:L("主要語言:繁中／簡中／日文","主要语言:繁中／简中／日文","主要言語:中国語／日本語","Primary: Chinese / Japanese") },
    { id:"admin", ic:"🛠️", cls:"n4",
      title:L("管理人後臺","管理人后台","管理者","Admin"),
      ja:"管理者アカウント",
      desc:L("最高權限。建立展覽、審核資料、補充現場資訊、控制誰能看到什麼。","最高权限。建立展览、审核资料、补充现场信息、控制谁能看到什么。","最高権限。展示会作成、データ審査、現場情報の補足、公開範囲の制御。","Full control. Create expos, review data, add on-site info, control visibility."),
      tag:L("主要語言:繁中","主要语言:繁中","主要言語:中国語","Primary: Chinese") }
  ],
  exhibitorPortal: {
    head: L("出展企業|展覽廠商入口","出展企业|展览厂商入口","出展企業アカウント","Exhibitor Portal"),
    langnote: L("主要語言:日文","主要语言:日文","主要言語:日本語","Primary language: Japanese"),
    desc: L("我們受台灣與中國大陸企業委託,於展覽現場蒐集商品與商務資料。請貴公司登錄商品資訊、公司資料、型錄、價格表與出口條件。",
      "我们受台湾与中国大陆企业委托,于展览现场搜集商品与商务资料。请贵公司登录商品信息、公司资料、样册、价格表与出口条件。",
      "私たちは台湾および中国大陸の企業から依頼を受け、展示会における製品・商務資料を収集しております。貴社の商品情報、会社資料、カタログ、価格表、輸出条件などをご登録ください。",
      "Commissioned by companies in Taiwan and mainland China, we collect product and business data at the expo. Please register your products, company profile, catalogs, price lists and export terms."),
    sec1: L("① 公司基本資料","① 公司基本资料","① 会社基本情報","① Company profile"),
    sec2: L("② 商品資料","② 商品资料","② 商品情報","② Product data"),
    f_company: L("公司名稱","公司名称","会社名","Company name"),
    f_booth: L("攤位","展位","ブース番号","Booth"),
    f_contact: L("聯絡窗口","联络窗口","担当者・連絡先","Contact"),
    f_category: L("品類","品类","カテゴリ","Category"),
    f_profile: L("公司簡介","公司简介","会社紹介","Company intro"),
    f_product: L("商品名稱","商品名称","商品名","Product name"),
    f_moq: L("最低訂購量 MOQ","最低订购量 MOQ","MOQ","MOQ"),
    f_wholesale: L("批發價","批发价","卸売価格","Wholesale price"),
    f_sample: L("樣品條件","样品条件","サンプル条件","Sample terms"),
    f_export: L("出口條件","出口条件","輸出条件","Export terms"),
    f_oem: L("OEM / ODM 條件","OEM / ODM 条件","OEM / ODM 条件","OEM / ODM terms"),
    f_catalog: L("型錄","样册","カタログ","Catalog"),
    f_pricelist: L("價格表","价格表","価格表","Price list"),
    f_photo: L("商品照片","商品照片","商品写真","Product photos"),
    f_video: L("商品影片","商品视频","商品動画","Product video"),
    btn_submit: L("提交資料","提交资料","提出する","Submit"),
    btn_edit: L("修改我的資料","修改我的资料","自分の資料を修正","Edit my data"),
    lockTitle: L("您看不到的內容","您看不到的内容","アクセス制限","Restricted from you"),
    lock: L("其他展商資料、委託採購廠商名單、管理者內部備註、商品評分、客戶收藏與詢問紀錄",
      "其他展商资料、委托采购厂商名单、管理者内部备注、商品评分、客户收藏与询问记录",
      "他の出展者の資料、バイヤー名簿、管理者の内部メモ、商品評価、顧客のお気に入り・問い合わせ記録",
      "Other exhibitors' data, buyer lists, admin internal notes, product ratings, client favorites and inquiries")
  },
  buyerPortal: {
    head: L("委託帶採購廠商入口","委托带采购厂商入口","調達依頼企業ポータル","Sourcing Buyer Portal"),
    langnote: L("主要語言:繁體中文／簡體中文","主要语言:繁体中文／简体中文","主要言語:中国語","Primary language: Chinese"),
    desc: L("這裡是 B2B 採購資料庫,不是一般商品展示網站。您看到的是管理者整理後、授權開放給您的專案資料。",
      "这里是 B2B 采购资料库,不是一般商品展示网站。您看到的是管理者整理后、授权开放给您的项目资料。",
      "ここはB2B調達データベースであり、一般展示サイトではありません。管理者が整理し許可した案件情報を表示します。",
      "This is a B2B sourcing database, not a public showcase. You see project data curated and authorized for you by the admin."),
    myProject: L("我的委託專案:","我的委托项目:","委託案件:","My project: "),
    cat: L("委託品類:","委托品类:","委託カテゴリ:","Focus: "),
    market: L("目標市場:","目标市场:","対象市場:","Market: "),
    authorized: L("授權商品","授权商品","許可商品","Authorized products"),
    booth: L("攤位","展位","ブース","Booth"),
    moq: L("MOQ","MOQ","MOQ","MOQ"),
    wholesale: L("批發","批发","卸売","Wholesale"),
    exportL: L("出口","出口","輸出","Export"),
    oem: L("OEM","OEM","OEM","OEM"),
    sample: L("樣品","样品","サンプル","Sample"),
    fitTw: L("適合台灣","适合台湾","台湾向き","Fits Taiwan"),
    fitCn: L("適合中國大陸","适合中国大陆","中国向き","Fits China"),
    follow: L("建議後續聯繫","建议后续联系","フォロー推奨","Follow up"),
    adminNote: L("管理者備註:","管理者备注:","管理者メモ:","Admin note: "),
    fav: L("收藏","收藏","お気に入り","Save"),
    request: L("提出採購需求","提出采购需求","調達依頼","Request quote"),
    lockTitle: L("您看不到的內容","您看不到的内容","閲覧不可","Restricted"),
    lock: L("無法直接修改展商原始資料、其他委託採購廠商的資料、管理者未審核的資料、其他客戶的收藏與詢價、未被授權的展覽專案",
      "无法直接修改展商原始资料、其他委托采购厂商的资料、管理者未审核的资料、其他客户的收藏与询价、未被授权的展览项目",
      "出展者の原本データの直接編集、他バイヤーの情報、未審査データ、他顧客のお気に入り・見積、未許可の展示会案件",
      "Editing exhibitor originals, other buyers' data, unreviewed data, other clients' favorites/quotes, unauthorized expo projects")
  },
  consumerPortal: {
    head: L("日本精選商品","日本精选商品","日本厳選商品","Selected Japanese Products"),
    langnote: L("主要語言:繁中／簡中／日文","主要语言:繁中／简中／日文","主要言語:中国語／日本語","Primary: Chinese / Japanese"),
    desc: L("嚴選日本好物,看商品特色、品牌故事與使用方式。(不顯示批發價、MOQ、代理與 OEM 等商務條件)",
      "严选日本好物,看商品特色、品牌故事与使用方式。(不显示批发价、MOQ、代理与 OEM 等商务条件)",
      "厳選した日本の逸品。特長・ブランドストーリー・使い方をご紹介。(卸価格・MOQ・代理・OEM等の商務条件は非表示)",
      "Curated Japanese goods — features, brand stories and usage. (Wholesale price, MOQ, agency and OEM terms are hidden.)"),
    feature: L("特色:","特色:","特長:","Features: "),
    usage: L("用法:","用法:","使い方:","Usage: "),
    fav: L("收藏","收藏","お気に入り","Save"),
    lockTitle: L("不顯示的內容","不显示的内容","非表示の内容","Hidden"),
    lock: L("批發價、MOQ、代理條件、OEM/ODM、商務價格表、展商完整商務聯絡、管理者內部評估、委託採購廠商專區",
      "批发价、MOQ、代理条件、OEM/ODM、商务价格表、展商完整商务联络、管理者内部评估、委托采购厂商专区",
      "卸価格、MOQ、代理条件、OEM/ODM、商務価格表、出展者の商務連絡先、管理者の内部評価、バイヤー専用エリア",
      "Wholesale price, MOQ, agency terms, OEM/ODM, business price lists, full exhibitor contacts, internal admin reviews, buyer-only area")
  },
  adminPortal: {
    head: L("管理者後臺","管理者后台","管理者ポータル","Admin Console"),
    langnote: L("主要語言:繁體中文","主要语言:繁体中文","主要言語:中国語","Primary language: Chinese"),
    desc: L("最高權限。最重要的職責是控制「誰可以看到什麼」。","最高权限。最重要的职责是控制「谁可以看到什么」。","最高権限。最も重要な役割は「誰が何を見られるか」の制御です。","Full control. The key duty is controlling who can see what."),
    exhMgmt: L("展覽專案管理","展览项目管理","展示会プロジェクト管理","Expo project management"),
    btnNewExpo: L("＋ 建立展覽專案","＋ 建立展览项目","＋ 展示会を作成","+ New expo project"),
    btnQR: L("建立 QR Code","建立 QR Code","QRコード作成","Create QR code"),
    btnExport: L("匯出報告","导出报告","レポート出力","Export report"),
    review: L("展商資料審核","展商资料审核","出展者データ審査","Exhibitor review"),
    th_exh: L("展商","展商","出展者","Exhibitor"),
    th_booth: L("攤位","展位","ブース","Booth"),
    th_cat: L("品類","品类","カテゴリ","Category"),
    th_status: L("狀態","状态","状態","Status"),
    th_op: L("操作","操作","操作","Action"),
    reviewed: L("已審核","已审核","審査済","Reviewed"),
    pending: L("待審核","待审核","審査待ち","Pending"),
    view: L("檢視","查看","表示","View"),
    doReview: L("審核","审核","審査","Review"),
    prodMgmt: L("商品資料管理 ＋ 可見權限設定","商品资料管理 ＋ 可见权限设定","商品データ管理＋公開権限設定","Product management + visibility"),
    prodHint: L("每筆商品 = 三種版本。勾選決定開放給誰、給哪個客戶(L4 指定客戶專屬)。",
      "每笔商品 = 三种版本。勾选决定开放给谁、给哪个客户(L4 指定客户专属)。",
      "各商品=3つの版。チェックで公開先・対象顧客(L4指定顧客限定)を決定。",
      "Each product = 3 versions. Checkboxes set who and which client (L4 client-specific) can view."),
    th_prod: L("商品","商品","商品","Product"),
    th_rec: L("推薦","推荐","推奨","Rec."),
    th_l1: L("L1 消費者","L1 消费者","L1 消費者","L1 Consumer"),
    th_l2: L("L2 B2B","L2 B2B","L2 B2B","L2 B2B"),
    th_l4: L("L4 指定客戶","L4 指定客户","L4 指定顧客","L4 Clients"),
    th_l3: L("內部備註(L3)","内部备注(L3)","内部メモ(L3)","Internal note (L3)"),
    open: L("☑ 開放","☑ 开放","☑ 公開","☑ Open"),
    closed: L("☐ 未開放","☐ 未开放","☐ 非公開","☐ Closed"),
    unreviewed: L("未審核","未审核","未審査","Unreviewed"),
    verbal: L("口頭:","口头:","口頭:","Verbal: "),
    attitude: L("態度:","态度:","態度:","Attitude: "),
    risk: L("風險:","风险:","リスク:","Risk: "),
    interested: L("有興趣客戶:","有兴趣客户:","関心顧客:","Interested: "),
    th_date: L("日期","日期","日程","Date"),
    th_venue: L("地點","地点","会場","Venue"),
    supplement: L("現場補充 / 後續追蹤","现场补充 / 后续追踪","現場補足 / フォローアップ","On-site notes / Follow-up"),
    supText: L("可補充:現場照片、影片、流程說明、口頭報價、展商態度與合作意願、推薦程度;建立客戶專屬查看權限 → 指定開放給 A / B 客戶;匯出報告、建立後續追蹤清單。",
      "可补充:现场照片、视频、流程说明、口头报价、展商态度与合作意愿、推荐程度;建立客户专属查看权限 → 指定开放给 A / B 客户;导出报告、建立后续追踪清单。",
      "補足可能:現場写真・動画、フロー説明、口頭見積、出展者の態度・協力意向、推奨度;顧客別の閲覧権限を作成 → A/B顧客へ指定公開;レポート出力、フォローリスト作成。",
      "Can add: on-site photos/videos, process notes, verbal quotes, exhibitor attitude/willingness, recommendation; create per-client view rights → grant to client A/B; export reports, build follow-up lists.")
  },
  permTitle: L("權限架構總表","权限架构总表","権限マトリクス","Permission Matrix"),
  permHeaders: L(
    ["功能 / 資料","展覽廠商","委託帶採購廠商","傳統消費者","管理人"],
    ["功能 / 资料","展览厂商","委托带采购厂商","传统消费者","管理人"],
    ["機能 / 情報","出展者","バイヤー","消費者","管理者"],
    ["Feature / Data","Exhibitor","Buyer","Consumer","Admin"]),
  // 權限儲存格代碼: Y=可 N=不可 X=不需要 a/b/c/d=有條件
  permRows: [
    { f:L("掃描 QR Code / 進入","扫描 QR Code / 进入","QR読取 / 入場","Scan QR / enter"), v:["Y","Y","Y","Y"] },
    { f:L("建立公司資料","建立公司资料","会社情報の作成","Create company data"), v:["a1","N","N","Y"] },
    { f:L("建立商品資料","建立商品资料","商品情報の作成","Create product data"), v:["a1","N","N","Y"] },
    { f:L("上傳型錄","上传样册","カタログ登録","Upload catalog"), v:["Y","N","N","Y"] },
    { f:L("上傳價格表","上传价格表","価格表登録","Upload price list"), v:["Y","N","N","Y"] },
    { f:L("查看其他展商資料","查看其他展商资料","他社情報の閲覧","View other exhibitors"), v:["N","a2","a3","Y"] },
    { f:L("查看批發價","查看批发价","卸価格の閲覧","View wholesale price"), v:["N","a4","N","Y"] },
    { f:L("查看 MOQ","查看 MOQ","MOQの閲覧","View MOQ"), v:["N","a4","N","Y"] },
    { f:L("查看 OEM/ODM 條件","查看 OEM/ODM 条件","OEM/ODM条件の閲覧","View OEM/ODM"), v:["N","a4","N","Y"] },
    { f:L("查看管理者備註","查看管理者备注","管理者メモの閲覧","View admin notes"), v:["N","a5","N","Y"] },
    { f:L("收藏商品","收藏商品","商品お気に入り","Save products"), v:["X","Y","a6","Y"] },
    { f:L("提出採購/詢問需求","提出采购/询问需求","調達・問合せ依頼","Request / inquire"), v:["N","Y","a7","Y"] },
    { f:L("補充現場照片/影片","补充现场照片/视频","現場写真・動画の補足","Add on-site media"), v:["N","N","N","Y"] },
    { f:L("審核資料","审核资料","データ審査","Review data"), v:["N","N","N","Y"] },
    { f:L("控制可見權限","控制可见权限","公開権限の制御","Control visibility"), v:["N","N","N","Y"] }
  ],
  permCode: {
    Y: L("可","可","可","Yes"),
    N: L("不可","不可","不可","No"),
    X: L("不需要","不需要","不要","N/A"),
    a1: L("可(僅自己)","可(仅自己)","可(自社のみ)","Yes (own only)"),
    a2: L("可(限授權)","可(限授权)","可(許可分のみ)","Yes (authorized)"),
    a3: L("可(限公開)","可(限公开)","可(公開分のみ)","Yes (public)"),
    a4: L("可(若開放)","可(若开放)","可(公開時)","Yes (if opened)"),
    a5: L("可(限開放)","可(限开放)","可(公開時)","Yes (if opened)"),
    a6: L("可(簡化版)","可(简化版)","可(簡易版)","Yes (basic)"),
    a7: L("可(簡化詢問)","可(简化询问)","可(簡易問合せ)","Yes (basic)")
  },
  footer: L("原型 Demo・資料為範例","原型 Demo・资料为范例","プロトタイプ・サンプルデータ","Prototype demo · sample data"),
  viewPerm: L("▸ 查看權限架構總表","▸ 查看权限架构总表","▸ 権限マトリクスを見る","▸ View permission matrix")
};

// ---------- 資料庫 ----------
window.DB = {
  exhibition: {
    name: L("JFEX SUMMER 2026 — 日本食品輸出EXPO / JFEX / Food LogiX",
            "JFEX SUMMER 2026 — 日本食品输出EXPO / JFEX / Food LogiX",
            "JFEX SUMMER 2026 —「日本の食品」輸出EXPO / JFEX / Food LogiX",
            "JFEX SUMMER 2026 — Japan Food Export EXPO / JFEX / Food LogiX"),
    date: "2026/6/24–6/26",
    venue: L("東京 Big Sight(東京國際展示場)","东京 Big Sight(东京国际展示场)","東京ビッグサイト","Tokyo Big Sight"),
    organizer: "RX Japan",
    scale: L("約700家參展商・約60國海外買家","约700家参展商・约60国海外买家","約700社出展・約60ヶ国の海外バイヤー","~700 exhibitors · buyers from ~60 countries"),
    status: L("進行中","进行中","開催中","Active")
  },
  buyers: [
    { id:"A", name:L("台灣優鮮食品進口(A客戶)","台湾优鲜食品进口(A客户)","台湾優鮮食品輸入(A顧客)","Taiwan Fresh Foods (Client A)"),
      focus:L("茶葉・飲料・調味料","茶叶・饮料・调味料","茶・飲料・調味料","Tea, beverages, seasonings"),
      market:L("台灣","台湾","台湾","Taiwan"), grants:["p001","p002","p005"] },
    { id:"B", name:L("康家介護機構(B客戶)","康家介护机构(B客户)","康家介護施設(B顧客)","Kangjia Care (Client B)"),
      focus:L("介護食・機能性食品","介护食・功能性食品","介護食・機能性食品","Care food, functional food"),
      market:L("台灣/中國大陸","台湾/中国大陆","台湾/中国大陸","Taiwan / China"), grants:["p003","p004"] },
    { id:"C", name:L("上海跨境電商(C客戶)","上海跨境电商(C客户)","上海越境EC(C顧客)","Shanghai Cross-border (Client C)"),
      focus:L("零食・人氣商品","零食・人气商品","スナック・人気商品","Snacks, trending items"),
      market:L("中國大陸","中国大陆","中国大陸","China"), grants:["p001","p002","p004","p005"] }
  ],
  exhibitors: [
    { id:"e01", booth:"E-12", reviewed:true,
      name:L("靜岡茶園股份有限公司","静冈茶园股份有限公司","静岡茶園株式会社","Shizuoka Tea Garden Co."),
      category:L("飲料・茶","饮料・茶","飲料・茶","Beverages / Tea") },
    { id:"e02", booth:"J-08", reviewed:true,
      name:L("北海道健康食品","北海道健康食品","北海道ヘルスフーズ","Hokkaido Health Foods"),
      category:L("機能性食品・介護食","功能性食品・介护食","機能性食品・介護食","Functional / Care food") },
    { id:"e03", booth:"F-21", reviewed:false,
      name:L("大阪零食工坊","大阪零食工坊","大阪スナック工房","Osaka Snack Works"),
      category:L("加工食品・零食","加工食品・零食","加工食品・スナック","Processed food / Snacks") }
  ],
  products: [
    { id:"p001", exhibitorId:"e01",
      name:L("特上 有機抹茶 100g","特上 有机抹茶 100g","特上 有機抹茶 100g","Premium Organic Matcha 100g"),
      consumer:{ image:"🍵",
        story:L("靜岡百年茶園,石臼研磨,色澤翠綠、香氣濃郁。","静冈百年茶园,石臼研磨,色泽翠绿、香气浓郁。","静岡の百年茶園、石臼挽き、鮮やかな緑と豊かな香り。","Century-old Shizuoka garden, stone-milled, vivid green and aromatic."),
        feature:L("有機認證・無添加・適合沖泡與烘焙","有机认证・无添加・适合冲泡与烘焙","有機認証・無添加・飲用と製菓に","Organic, additive-free, for drinking & baking"),
        origin:L("日本・靜岡縣","日本・静冈县","日本・静岡県","Shizuoka, Japan"),
        usage:L("80℃熱水沖泡,或用於甜點烘焙","80℃热水冲泡,或用于甜点烘焙","80℃のお湯で点てる、製菓にも","Brew at 80℃ or use in baking"),
        price:L("參考售價 ¥2,160/罐","参考售价 ¥2,160/罐","参考価格 ¥2,160/缶","Ref. ¥2,160/can"),
        buy:L("官方旗艦店 / 詢問表單","官方旗舰店 / 询问表单","公式ストア / 問合せ","Official store / inquiry") },
      b2b:{ moq:L("100罐","100罐","100缶","100 cans"),
        wholesale:L("¥1,180/罐(未稅)","¥1,180/罐(未税)","¥1,180/缶(税抜)","¥1,180/can (excl. tax)"),
        sample:L("可提供樣品3罐,運費買方負擔","可提供样品3罐,运费买方负担","サンプル3缶可、送料は買主負担","3 samples, buyer pays shipping"),
        exportT:L("可出口台灣/中國大陸,需冷藏物流","可出口台湾/中国大陆,需冷藏物流","台湾/中国へ輸出可、冷蔵物流","Export to TW/CN, needs cold chain"),
        oem:L("支援OEM貼牌,MOQ 500罐起","支持OEM贴牌,MOQ 500罐起","OEM対応、MOQ 500缶~","OEM available, MOQ 500+"),
        adminNote:L("現場試飲品質佳,茶農配合度高;建議台灣高端茶飲通路。","现场试饮品质佳,茶农配合度高;建议台湾高端茶饮通路。","試飲good、茶農の協力的;台湾の高級茶チャネル推奨。","Great tasting on-site, cooperative grower; suits premium TW tea channels."),
        recommend:5, fit_tw:true, fit_cn:true, follow:true },
      admin:{ verbal:L("口頭可談到 ¥1,050/罐(量大)","口头可谈到 ¥1,050/罐(量大)","口頭で¥1,050/缶(大口)","Verbal ¥1,050/can (bulk)"),
        attitude:L("積極,願長期合作","积极,愿长期合作","積極的、長期希望","Eager, wants long-term"),
        risk:L("產量有上限,旺季可能缺貨","产量有上限,旺季可能缺货","生産上限あり、繁忙期欠品の恐れ","Capacity capped, peak shortages"),
        interested:["A","C"] } },
    { id:"p002", exhibitorId:"e01",
      name:L("深蒸煎茶 茶包","深蒸煎茶 茶包","深蒸し煎茶 ティーバッグ","Deep-steamed Sencha Teabags"),
      consumer:{ image:"🫖",
        story:L("便利茶包,辦公室與居家皆宜。","便利茶包,办公室与居家皆宜。","便利なティーバッグ、オフィスにも家庭にも。","Convenient teabags for office and home."),
        feature:L("三角立體茶包・冷泡熱泡皆可","三角立体茶包・冷泡热泡皆可","三角ティーバッグ・水出し/お湯出し可","Pyramid bags, hot or cold brew"),
        origin:L("日本・靜岡縣","日本・静冈县","日本・静岡県","Shizuoka, Japan"),
        usage:L("冷泡或熱泡均可","冷泡或热泡均可","水出し・お湯出しどちらも","Cold or hot brew"),
        price:L("參考售價 ¥980/盒","参考售价 ¥980/盒","参考価格 ¥980/箱","Ref. ¥980/box"),
        buy:L("官方旗艦店","官方旗舰店","公式ストア","Official store") },
      b2b:{ moq:L("200盒","200盒","200箱","200 boxes"),
        wholesale:L("¥520/盒(未稅)","¥520/盒(未税)","¥520/箱(税抜)","¥520/box (excl. tax)"),
        sample:L("可提供樣品2盒","可提供样品2盒","サンプル2箱可","2 sample boxes"),
        exportT:L("可出口台灣/中國大陸,常溫物流","可出口台湾/中国大陆,常温物流","台湾/中国へ輸出可、常温物流","Export TW/CN, ambient logistics"),
        oem:L("支援ODM客製包裝,MOQ 1000盒","支持ODM定制包装,MOQ 1000盒","ODM包装対応、MOQ 1000箱","ODM packaging, MOQ 1000+"),
        adminNote:L("適合電商通路,單價低、好上架。","适合电商通路,单价低、好上架。","EC向き、単価安く扱いやすい。","Good for e-commerce, low price, easy to list."),
        recommend:4, fit_tw:true, fit_cn:true, follow:true },
      admin:{ verbal:L("¥480/盒(量大)","¥480/盒(量大)","¥480/箱(大口)","¥480/box (bulk)"),
        attitude:L("積極","积极","積極的","Eager"),
        risk:L("無明顯風險","无明显风险","目立つリスクなし","No notable risk"),
        interested:["A","C"] } },
    { id:"p003", exhibitorId:"e02",
      name:L("軟質介護食 鮭魚粥","软质介护食 鲑鱼粥","やわらか介護食 鮭おかゆ","Soft Care Food: Salmon Porridge"),
      consumer:{ image:"🥣",
        story:L("為長者設計的易嚥營養餐。","为长者设计的易咽营养餐。","高齢者向けの飲み込みやすい栄養食。","Easy-to-swallow nutrition for seniors."),
        feature:L("易吞嚥・高蛋白・常溫保存","易吞咽・高蛋白・常温保存","嚥下対応・高たんぱく・常温保存","Easy swallow, high protein, ambient"),
        origin:L("日本・北海道","日本・北海道","日本・北海道","Hokkaido, Japan"),
        usage:L("隔水加熱即食","隔水加热即食","湯せんで温めて","Warm in water bath, ready to eat"),
        price:L("參考售價 ¥380/份","参考售价 ¥380/份","参考価格 ¥380/食","Ref. ¥380/serving"),
        buy:L("詢問表單","询问表单","問合せ","Inquiry") },
      b2b:{ moq:L("500份","500份","500食","500 servings"),
        wholesale:L("¥210/份(未稅)","¥210/份(未税)","¥210/食(税抜)","¥210/serving (excl. tax)"),
        sample:L("可提供樣品5份","可提供样品5份","サンプル5食可","5 samples"),
        exportT:L("可出口台灣/中國大陸,需食品標示翻譯","可出口台湾/中国大陆,需食品标示翻译","台湾/中国へ輸出可、食品表示の翻訳要","Export TW/CN, label translation needed"),
        oem:L("支援OEM,MOQ 2000份","支持OEM,MOQ 2000份","OEM対応、MOQ 2000食","OEM available, MOQ 2000+"),
        adminNote:L("HACCP認證齊全,適合介護機構與醫療通路。","HACCP认证齐全,适合介护机构与医疗通路。","HACCP取得済、介護施設・医療チャネル向き。","HACCP certified, suits care/medical channels."),
        recommend:5, fit_tw:true, fit_cn:true, follow:true },
      admin:{ verbal:L("¥190/份(年約)","¥190/份(年约)","¥190/食(年契約)","¥190/serving (annual)"),
        attitude:L("非常積極,有意設台灣總代理","非常积极,有意设台湾总代理","非常に積極的、台湾総代理を希望","Very eager, wants TW master agency"),
        risk:L("需確認進口食品法規","需确认进口食品法规","輸入食品規制の確認要","Verify import food regulations"),
        interested:["B"] } },
    { id:"p004", exhibitorId:"e02",
      name:L("長者營養果凍","长者营养果冻","高齢者向け 栄養ゼリー","Senior Nutrition Jelly"),
      consumer:{ image:"🍮",
        story:L("一口補充營養的果凍。","一口补充营养的果冻。","一口で栄養補給できるゼリー。","A jelly that delivers nutrition in one bite."),
        feature:L("高熱量・好入口・多口味","高热量・好入口・多口味","高カロリー・食べやすい・多味","High calorie, easy to eat, many flavors"),
        origin:L("日本・北海道","日本・北海道","日本・北海道","Hokkaido, Japan"),
        usage:L("開封即食","开封即食","開封してそのまま","Open and eat"),
        price:L("參考售價 ¥150/個","参考售价 ¥150/个","参考価格 ¥150/個","Ref. ¥150/each"),
        buy:L("詢問表單","询问表单","問合せ","Inquiry") },
      b2b:{ moq:L("1000個","1000个","1000個","1000 units"),
        wholesale:L("¥78/個(未稅)","¥78/个(未税)","¥78/個(税抜)","¥78/unit (excl. tax)"),
        sample:L("可提供樣品一組6入","可提供样品一组6入","サンプル6個入1組可","1 sample pack of 6"),
        exportT:L("可出口台灣/中國大陸","可出口台湾/中国大陆","台湾/中国へ輸出可","Export to TW/CN"),
        oem:L("支援ODM口味客製,MOQ 5000個","支持ODM口味定制,MOQ 5000个","ODM味カスタム対応、MOQ 5000個","ODM flavor custom, MOQ 5000+"),
        adminNote:L("毛利高,適合介護與電商雙通路。","毛利高,适合介护与电商双通路。","粗利高、介護とECの両チャネル向き。","High margin, suits care + e-commerce."),
        recommend:4, fit_tw:true, fit_cn:true, follow:true },
      admin:{ verbal:L("¥70/個(量大)","¥70/个(量大)","¥70/個(大口)","¥70/unit (bulk)"),
        attitude:L("積極","积极","積極的","Eager"),
        risk:L("冷鏈非必要,常溫即可","冷链非必要,常温即可","冷蔵不要、常温で可","No cold chain needed"),
        interested:["B","C"] } },
    { id:"p005", exhibitorId:"e03",
      name:L("醬油仙貝禮盒","酱油仙贝礼盒","醤油せんべい 詰合せ","Soy-sauce Senbei Gift Box"),
      consumer:{ image:"🍘",
        story:L("傳統炭烤醬油仙貝。","传统炭烤酱油仙贝。","伝統の炭火焼き醤油せんべい。","Traditional charcoal-grilled soy senbei."),
        feature:L("炭烤香氣・酥脆・送禮自用兩相宜","炭烤香气・酥脆・送礼自用两相宜","炭火の香ばしさ・サクサク・贈答にも","Charcoal aroma, crisp, great for gifts"),
        origin:L("日本・大阪","日本・大阪","日本・大阪","Osaka, Japan"),
        usage:L("開封即食","开封即食","開封してそのまま","Open and eat"),
        price:L("參考售價 ¥1,080/盒","参考售价 ¥1,080/盒","参考価格 ¥1,080/箱","Ref. ¥1,080/box"),
        buy:L("官方旗艦店","官方旗舰店","公式ストア","Official store") },
      b2b:{ moq:L("100盒","100盒","100箱","100 boxes"),
        wholesale:L("¥560/盒(未稅)","¥560/盒(未税)","¥560/箱(税抜)","¥560/box (excl. tax)"),
        sample:L("可提供樣品2盒","可提供样品2盒","サンプル2箱可","2 sample boxes"),
        exportT:L("可出口台灣/中國大陸,常溫物流","可出口台湾/中国大陆,常温物流","台湾/中国へ輸出可、常温物流","Export TW/CN, ambient logistics"),
        oem:L("OEM/ODM皆可,小批量對應,MOQ 300盒","OEM/ODM皆可,小批量对应,MOQ 300盒","OEM/ODM可、小ロット対応、MOQ 300箱","OEM/ODM ok, small lots, MOQ 300+"),
        adminNote:L("小批量友善,適合新進口商試單。","小批量友善,适合新进口商试单。","小ロット可、新規輸入業者の試し買い向き。","Small-lot friendly, good for new importers' trial."),
        recommend:3, fit_tw:true, fit_cn:true, follow:false, unreviewed:true },
      admin:{ verbal:L("¥520/盒","¥520/盒","¥520/箱","¥520/box"),
        attitude:L("一般","一般","普通","Neutral"),
        risk:L("資料尚未審核完成","资料尚未审核完成","データ未審査","Data not yet reviewed"),
        interested:["A","C"] } }
  ]
};
